data:
#    name: 'Uz_repeatability_dataset'
    dataset: 'Uz_repeatability_dataset'  # 'hpatches' 'coco'
#    alteration: 'all'  # 'i' 'v' 'all'
    cache_in_memory: false
#    validation_size: 100
    preprocessing:
        resize: [256, 256]  # False for coco
#        resize: [480, 640]  # False for coco
model:
    name: 'classical_detectors_descriptors'
    method: 'orb'  # 'orb' 'sift'
    batch_size: 1  # unused
    learning_rate: 0.001  # unused
    nms: 0
    top_k: 1000
eval_iter: 1000
seed: 1
